package mfli.behaviortree;

public class Constants {
	public static String CURRENT_PLAYER_POSITION = "CURRENT_PLAYER_POSITION";
	public static String NEAREST_GHOST_LOCATION = "NEAREST_GHOST_LOCATION";
	public static String NEAREST_GHOST_DISTANCE = "NEAREST_GHOST_DISTANCE";
	public static String NEAREST_GHOST = "NEAREST_GHOST";
	public static String MIN_GHOST_DISTANCE_BEFORE_FLEE = "MIN_GHOST_DISTANCE_BEFORE_FLEE";
	public static String MIN_GHOST_DISTANCE_BEFORE_ATTACK = "MIN_GHOST_DISTANCE_BEFORE_ATTACK";
	public static String NEAREST_POWER_PILL_LOCATION = "NEAREST_POWER_PILL_LOCATION";
	public static String NEAREST_POWER_PILL_DISTANCE = "NEAREST_POWER_PILL_DISTANCE";
	public static String MIN_POWER_PILL_DISTANCE_BEFORE_EAT = "MIN_POWER_PILL_DISTANCE";
	public static String NEAREST_PILL_LOCATION = "NEAREST_PILL_LOCATION";
	public static String NEAREST_PILL_DISTANCE = "NEAREST_PILL_DISTANCE";
	
	public static String NEXT_MOVE = "NEXT_MOVE";
	public static String THREATENING_GHOSTS = "THREATENING_GHOSTS";
	public static String VICTIM_GHOSTS = "VICTIM_GHOSTS";
	public static String CLOSEST_POWER_PILL_POSITION = "CLOSEST_POWER_PILL_POSITION";
	public static String CLOSEST_PILL_POSITION = "CLOSEST_PILL_POSITION";
}
